module.exports = {
    swaggerDefinition: {
      // 정보
      openapi: '3.0.0',
      info: {
        title: 'Flogging Server api list',
        version: '1.0.0',
        description: 'Flogging Server api list'
      },
      // 주소
      host: "localhost:3000",
      // 기본 root path
      basePath: "/",
      contact: {
        email: "xowns4817@naver.com"
      },
      // 각 api에서 설명을 기록할 때 사용할 constant들을 미리 등록해놓는것
      schemes: ["http", "https"], // 가능한 통신 방식
    },
    apis: ['.trash.js'] // api 파일 위치들 
  };
